### ISSUE TITLE
Native splash ad can't get content of 'screenshots'

### ISSUE THREAD

**Issue by nanako889** [InMobi/sdk-sample-code-android#11]
[{"icon":{"aspectRatio":1,"url":"http:\/\/i.l.inmobicdn.net\/uac-assets\/com.supercell.clashofclans-cn-1496318643928","height":150,"width":150},"isVideo":true,"adExpiryTime":"1509791056"}]

you can find that the 'screenshots' is missing but only 'icon'.
Why?

**Comment by SwagatoMondal** [comment]
Closing this as reported format isn't supported anymore.
