### ISSUE TITLE
Publisher handler caused unexpected error

### ISSUE THREAD

**Issue by amitsri20** [InMobi/sdk-sample-code-android#16]
Inmobi integrated successfully but getting this exception while creating object of AdFeedItem
`AdFeedItem adFeedItem = new AdFeedItem(inMobiNativeStrand);`

**Comment by SwagatoMondal** [comment]
This means there's something you're doing wrong when the callback is provided back by the SDK, which in turn is causing a crash. Please add try/catch in the call-backs you've implemented in order to debug.
