### ISSUE TITLE
Show in feed ads in recyclerview 

### ISSUE THREAD

**Issue by jerin6392** [InMobi/sdk-sample-code-android#20]
How to show in feed ads to recyclerview custom positions in android?

**Comment by davendarojha** [comment]
Please check `RecyclerFeedFragment` class for recyclerview feed integration.

**Comment by jerin6392** [comment]
I already checked it.But its not working correctly.I need to show ads after every 5 posts.

**Comment by SwagatoMondal** [comment]
In case you've already referred to this [file](https://github.com/InMobi/sdk-sample-code-android/blob/master/samples/nativeSample/src/main/java/com/inmobi/nativead/sample/recyclerview/RecyclerFeedFragment.java) and it's still not working, please contact your partner manager or PSO team of InMobi.
