### ISSUE TITLE
Does Rewarded Video Ad support  rotation for  landscape orientation?

### ISSUE THREAD

**Issue by leoqchen** [InMobi/sdk-sample-code-android#22]
Hi, 

I found that rewarded video ad only show on a fixed landscape orientation,  it can't rotation to another landscape orientation based on the phone/sensor direction. How to make the ad to rotate to another landscape direction?

Thanks for your guys' great work on InMobi.

**Comment by SwagatoMondal** [comment]
Hey, we don't support changing the change of orientation at runtime. The orientation of the ad is dictated by the ad response & is constant for an ad.
