### ISSUE TITLE
Banner XML integration is not working

### ISSUE THREAD

**Issue by ShahoodulHassan** [InMobi/sdk-sample-code-android#25]
Banner ads are not working via XML, with or with 'plid-'.
It always returns "inMobiBanner could not be initialized. Ignoring your call"

Please fix it!

**Comment by AnmLobby** [comment]
I have the same problem. Have you solved it?

**Comment by SwagatoMondal** [comment]
Thanks for the comment, we'll update the repo with the changes required (if any).

**Comment by rajsuvariya** [comment]
@ShahoodulHassan This happens when the InMobiBanner object is created before calling init on InMobiSdk. A common cause of the problem is adding InMobiBanner in XML and calling setContentView() before calling InMobiSdk.init(). So move your init code before creating the view.

**Comment by ShahoodulHassan** [comment]
Hi,

Thanks for replying but don't u think 06 months is an unreasonable response
time?

I'm sorry but I've moved on.
