### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by DeevD** [InMobi/sdk-sample-code-android#27]
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************

**Comment by pkleczko** [comment]
Hi, did you manage to resolve the problem? I have the same issue with 8.0.9 version...

**Comment by pkleczko** [comment]
Ok, I found a solution. You need to point that you are using Google Ad Manager instead of AdMob like below. Documentation is missing this:

Add this to AndroidManiest.xml
`<meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true" />`

**Comment by SwagatoMondal** [comment]
Earlier we had a dependency on **ads** module, but we've updated the integration guidelines to just use **ads-identifier** for IM pubs. In case you update the dependency as mentioned, then you will not be facing the issue mentioned. Hence closing this.
Guideline : https://support.inmobi.com/monetize/android-guidelines/
