### ISSUE TITLE
aar and jar wasn't the same version

### ISSUE THREAD

**Issue by zmer007** [InMobi/sdk-sample-code-android#28]
Hey, guys. In this repository, I found the jar version is 7.2.1 but the aar version is 7.2.0 , and the newest version is 7.2.2 which I can't found the version anywhere. I want to update my InMobi SDK, could you give me a suggestion which one should I integrate?

**Comment by SwagatoMondal** [comment]
Thanks for the comment, we'll update the repo with the latest details soon.

**Comment by SwagatoMondal** [comment]
Versions have been updated.
