### ISSUE TITLE
[InMobi]: Listener was garbage collected. Unable to give callback

### ISSUE THREAD

**Issue by BCsl** [InMobi/sdk-sample-code-android#30]
Cannot get callback when loading an ad. Library version : `com.inmobi.monetization:inmobi-ads:7.2.2`
Log with `[InMobi]: Listener was garbage collected. Unable to give callback`

**Comment by SwagatoMondal** [comment]
Hi @BCsl , there's a high chance that you're not declaring the ad object as a member variable and that is why maybe the local variable is garbage collected & thus no callbacks.

**Comment by AshishDhanani** [comment]
Listener was garbage collected. Unable to give callback

what is solution?

**Comment by SwagatoMondal** [comment]
1) Make sure you ad object is not a method variable which is supposed to be garbage collected at the end of the execution of the method.
2) The same applies for the listener you pass for each of these ad objects.
3) Please refer to the last comment, if you still have doubt please share sample code of the integration.

**Comment by AshishDhanani** [comment]
public void showAds(Activity a,CallBack back){

InMobiInterstitial  interstitialAd = new InMobiInterstitial(context, ID, new InterstitialAdEventListener() {
                @Override
                public void onAdLoadSucceeded(InMobiInterstitial inMobiInterstitial) {
                    super.onAdLoadSucceeded(inMobiInterstitial);
                    if(progressDialogNew!=null){
                        progressDialogNew.setMessage("Please Wait..!!");
                    }
                    inMobiInterstitial.show();
                }

                @Override
                public void onAdLoadFailed(InMobiInterstitial inMobiInterstitial, InMobiAdRequestStatus inMobiAdRequestStatus) {
                    super.onAdLoadFailed(inMobiInterstitial, inMobiAdRequestStatus);
                    if(progressDialogNew!=null){
                        progressDialogNew.dismiss();
                    }
                    try {
                        if (myCallbackfinal[0] != null) {
                            myCallbackfinal[0].callbackCallfinal();
                            myCallbackfinal[0] = null;
                        }
                        setdelay();
                 
                        isloading = true;

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }

                @Override
                public void onAdClicked(InMobiInterstitial inMobiInterstitial, Map<Object, Object> map) {
                    super.onAdClicked(inMobiInterstitial, map);
                }

                @Override
                public void onAdDisplayed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDisplayed(inMobiInterstitial);

                }

                @Override
                public void onAdDisplayFailed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDisplayFailed(inMobiInterstitial);
                }

                @Override
                public void onAdDismissed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDismissed(inMobiInterstitial);
                    setdelay();
                    if(progressDialogNew!=null){
                        progressDialogNew.dismiss();
                        progressDialogNew=null;
                    }

                    try {
                        if (myCallbackfinal[0] != null) {
                            myCallbackfinal[0].callbackCallfinal();
                            myCallbackfinal[0] = null;
                        }
                      
                        isloading = true;

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                @Override
                public void onRewardsUnlocked(InMobiInterstitial inMobiInterstitial, Map<Object, Object> map) {
                    super.onRewardsUnlocked(inMobiInterstitial, map);
                    Log.e("Ads", "Read,yes");
                }

                @Override
                public void onUserLeftApplication(InMobiInterstitial inMobiInterstitial) {
                    super.onUserLeftApplication(inMobiInterstitial);

                    Log.e("Ads", "Leave,yes");
                }
            });
            interstitialAd.load();
}

**Comment by AshishDhanani** [comment]
sorry i can't not understand so i share my code


InMobiInterstitial  interstitialAd = new InMobiInterstitial(context, IDL, new InterstitialAdEventListener() {
                @Override
                public void onAdLoadSucceeded(InMobiInterstitial inMobiInterstitial) {
                    super.onAdLoadSucceeded(inMobiInterstitial);
                    if(progressDialogNew!=null){
                        progressDialogNew.setMessage("Please Wait..!!");
                    }
                    inMobiInterstitial.show();
                }

                @Override
                public void onAdLoadFailed(InMobiInterstitial inMobiInterstitial, InMobiAdRequestStatus inMobiAdRequestStatus) {
                    super.onAdLoadFailed(inMobiInterstitial, inMobiAdRequestStatus);
                    if(progressDialogNew!=null){
                        progressDialogNew.dismiss();
                    }
                    try {
                        if (myCallbackfinal[0] != null) {
                            myCallbackfinal[0].callbackCallfinal();
                            myCallbackfinal[0] = null;
                        }
                        setdelay();
                        Log.d("AdStatus", "FB Ad Load");
                        isloading = true;

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }

                @Override
                public void onAdClicked(InMobiInterstitial inMobiInterstitial, Map<Object, Object> map) {
                    super.onAdClicked(inMobiInterstitial, map);
                }

                @Override
                public void onAdDisplayed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDisplayed(inMobiInterstitial);

                }

                @Override
                public void onAdDisplayFailed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDisplayFailed(inMobiInterstitial);
                }

                @Override
                public void onAdDismissed(InMobiInterstitial inMobiInterstitial) {
                    super.onAdDismissed(inMobiInterstitial);
                    setdelay();
                    if(progressDialogNew!=null){
                        progressDialogNew.dismiss();
                        progressDialogNew=null;
                    }

                    try {
                        if (myCallbackfinal[0] != null) {
                            myCallbackfinal[0].callbackCallfinal();
                            myCallbackfinal[0] = null;
                        }
                        Log.d("AdStatus", "FB Ad Load");
                        isloading = true;

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                @Override
                public void onRewardsUnlocked(InMobiInterstitial inMobiInterstitial, Map<Object, Object> map) {
                    super.onRewardsUnlocked(inMobiInterstitial, map);
                    Log.e("Ads", "Read,yes");
                }

                @Override
                public void onUserLeftApplication(InMobiInterstitial inMobiInterstitial) {
                    super.onUserLeftApplication(inMobiInterstitial);

                    Log.e("Ads", "Leave,yes");
                }
            });
            interstitialAd.load();

**Comment by SwagatoMondal** [comment]
Please declare this as member variable of your class -
```
public class XYZ extends Activity {
    private InMobiInterstitial interstitialAd;
    // .... other code
}
```

**Comment by AshishDhanani** [comment]
i put allready global variable but one more issue

like when ads show after add dismis then Listener 
 like     @Override
            public void onAdDismissed(InMobiInterstitial inMobiInterstitial) {}

exmple user ads close after 1 or 2 sec call above method but issue onAdDismissed after close ads more then 20 or 30 sec then i Listener call that is issue 

sort:-  after close button click lister response 30 or 20 sen after

**Comment by SwagatoMondal** [comment]
I'm really sorry but I'm unable to understand what you're saying, please refer to this [file](https://github.com/InMobi/sdk-sample-code-android/blob/master/samples/interstitialSample/src/main/java/com/inmobi/interstitial/sample/InterstitialAdsActivity.java) for integration reference. Thanks for contacting us.

**Comment by AshishDhanani** [comment]
Ads show then close button click then InterstitialAdEventListener response after close button click30 or 20
