### ISSUE TITLE
CursorWindowAllocationException

### ISSUE THREAD

**Issue by Armen101** [InMobi/sdk-sample-code-android#35]
com.inmobi.b.b.b.a.a (InitConfigurationDBHelper.java:248)
com.inmobi.commons.a.a.a (SdkContext.java:2170)
com.inmobi.ads.e.b.a (AdPreFetcher.java:8252)
com.inmobi.ads.e.b$4.run (AdPreFetcher.java:281)

**Comment by SwagatoMondal** [comment]
Hi @Armen101 thanks for letting us know, we're already working on it. We're gonna fix the issue in the upcoming version of the SDK.

**Comment by Armen101** [comment]
Thanks!  I'll wait

**Comment by lakshya21** [comment]
Hey @Armen101, the issue is fixed in the latest release. You can go ahead and update the sdk with the latest version.
