### ISSUE TITLE
dependencies not fond

### ISSUE THREAD

**Issue by luck-apple** [InMobi/sdk-sample-code-android#37]
build.gradle dependencies:
implementation 'com.google.android.gms:play-services-basement:16.2.0'
implementation 'com.google.android.gms:play-services-ads:17.2.1'
implementation 'com.google.android.gms:play-services-location:16.0.0'
implementation 'com.google.android.gms:play-services-plus:16.0.0'

Interstitial ad load failed: 
InMobi, onAdLoadFailed: The SDK rejected the ad request as one or more required dependencies could not be found. Please ensure you have included the required dependencies

**Comment by rajsuvariya** [comment]
Hi @luck-apple, 

You must have to add RecyclerView and Picasso in order to use Interstitial ads as mentioned on the docs https://support.inmobi.com/monetize/android-guidelines/

Please add the required libraries and try again.
