### ISSUE TITLE
"Ad request successful but no ad served" - issue fetching Interstitial ads in Android emulator

### ISSUE THREAD

**Issue by nmfisher** [InMobi/sdk-sample-code-android#38]
I've been writing a Flutter plugin that wraps the InMobiSDK for both iOS and Android (see https://github.com/nmfisher/inmobi_flutter_plugin).

Whenever I fetch an interstitial ad on the Android emulator, the following error is logged to the console:

```D/Interstitial( 5101): Unable to load interstitial ad (error message: Ad request successful but no ad served.```

The InMobi account is in Global Test Mode. The same request works fine on a real iOS device. I don't have an Android device with me right now to test, so I can't confirm if this happens outside the emulator.

Did InMobi disable serving ads (even test ads) to the Android emulator? If so, that would explain the behaviour and should be documented. 

If not, it means I have an issue on the plugin end that I haven't picked up on yet.

**Comment by shealyrd** [comment]
I have been having the same "Ad request successful but no ad served" error both on real Android devices and in the Android emulator. Even though the error says "Ad request successful", I do not see my test requests in the dashboard. My placements are also in Global Test Mode. 

@nmfisher Did you ever solve your error? I've contacted inMobi support about this issue but they have not responded yet.

**Comment by nmfisher** [comment]
@shealyrd I also lodged a support ticket and was told I needed to add an app URL via the dashboard ( Monetize --> App name --> Configuration --> App URL --> Edit).

Problem is, I think they expect an App Store/Play Store URL, which is only available when the app is published - but I don't think I can/should publish until I know the InMobi SDK is properly integrated. Sort of catch 22.

**Comment by RyanLeefy** [comment]
I have the same issue which shows "Ad request successful but no ad served". And I have already add the app URL.
@nmfisher  Did you have any other way to slove this problem?

**Comment by kyhnlbyrk** [comment]
Hi guys,

I am also facing this problem. Eventhough my app is global on testing, and my URL is my realy app URL from google play store.

It says ad request successfull but I am not seeing any requests on the web-site.

Any solution?

**Comment by SwagatoMondal** [comment]
Hi guys,

Apologies for replying late on this issue but currently there's a limitation that InMobi Server will respond with No-Fill for Android Emulators thinking it's an attempt to fraud (even though you might be using test placementID). Workaround for now can only be to use a real device.

Hence closing this issue as there won't be change in logic in near future.

**Comment by mingxin-yang** [comment]
@SwagatoMondal I face this problem in a real device
