### ISSUE TITLE
The following classes could not be instantiated Error. 

### ISSUE THREAD

**Issue by tenzinzero1** [InMobi/sdk-sample-code-android#4]
The following classes could not be instantiated:
- com.inmobi.ads.InMobiBanner (Open Class, Show Exception, Clear Cache)

1:Project clean and rebuild done. (Still error) 
App level gradle file... 
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.example.hello.test"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile "com.squareup.picasso:picasso:2.5.2"
    compile 'com.inmobi.monetization:inmobi-ads:6.2.0'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    testCompile 'junit:junit:4.12'
}
` 

Xml code..  

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:ads="http://schemas.android.com/apk/lib/com.inmobi.ads"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:mContext=".BannerXmlActivity">

    <TextView
        android:text="@string/banner_xml_message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

    <com.inmobi.ads.InMobiBanner
        android:id="@+id/banner"
        android:layout_width="320dp"
        android:layout_height="50dp"
        ads:placementId="1462507216771"
        ads:refreshInterval="60"/>

</LinearLayout>`

**Comment by SwagatoMondal** [comment]
Refer this [issue](https://github.com/InMobi/sdk-sample-code-android/issues/25) or refer to the integration [guidelines](https://support.inmobi.com/monetize/android-guidelines/banner-ads-for-android/).
