### ISSUE TITLE
Program type already present AerServBanner

### ISSUE THREAD

**Issue by moldis** [InMobi/sdk-sample-code-android#43]
I have a project with two AD providers AerServ and InMobi. In latest vesion i am getting this issue during build

AGPBI: {"kind":"error","text":"Program type already present: com.aerserv.sdk.AerServBanner$2","sources":[{}],"tool":"D8"}

**Comment by rajsuvariya** [comment]
Can you please provide versions of both the SDKs you are using?

**Comment by SwagatoMondal** [comment]
Closing this as there was no update.
