### ISSUE TITLE
Real ads

### ISSUE THREAD

**Issue by aniketshewale85** [InMobi/sdk-sample-code-android#53]
Test ads are working fine but real ads are not showing.

**Comment by SwagatoMondal** [comment]
Can you add more details? Like ad format, placementId, accountID. Also do give it one more try if you were facing issues with Banner format, unfortunately we did encounter some issue recently. But that issue was fixed, to get result you need to wait for one day or clear data.

**Comment by aniketshewale85** [comment]
Thank you for response.
It is fixed now. Ads started serving after one day

**Comment by SwagatoMondal** [comment]
Thanks for the confirmation, hence closing the issue.
