### ISSUE TITLE
ClassNotFoundException ImIdShareBroadCastReceiver

### ISSUE THREAD

**Issue by avioraboo** [InMobi/sdk-sample-code-android#57]
We started getting many errors like this:

Caused by java.lang.ClassNotFoundException
Didn't find class "com.inmobi.commons.core.utilities.uid.ImIdShareBroadCastReceiver" on path: DexPathList[[zip file "/data/app/com.eyecon.global-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eyecon.global-1/lib/arm, /data/app/com.eyecon.global-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:511)
java.lang.ClassLoader.loadClass (ClassLoader.java:469)
android.app.ActivityThread.handleReceiver (ActivityThread.java:2715)
android.app.ActivityThread.access$1800 (ActivityThread.java:157)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1428)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5437)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by SwagatoMondal** [comment]
Hi @avioraboo,if you've recently migrated from a **7XX** version **8XX+** version of the SDK, then you've to remove all the InMobi related entries from the `AndroidManifest.xml`. The sole reason being that we've migrated from **JAR** to **AAR** (which you might have already noticed).

**Comment by SwagatoMondal** [comment]
Closing issue by assuming the issue was resolved.
