### ISSUE TITLE
Callbacks doesn't work starting v.9.0.5

### ISSUE THREAD

**Issue by prilaga** [InMobi/sdk-sample-code-android#60]
Hi,
@SwagatoMondal 

I use BannerAdEventListener and InterstitialAdEventListener to check that ad is working properly.
In v.9.0.4 I receive all the information from callbacks, but starting with v.9.0.5 the methods from these callbacks no longer work. I can't receive that the onAdLoadFailed for banner and interstitial ad they were called.

**Comment by SwagatoMondal** [comment]
You should still be receiving the callbacks for the same listener, is it possible for you to share a sample code for the same?
Majorly the reason behind not receiving callbacks has been that the ad object was a local variable and was garbage collected. So possibly watch out for your integration in case the object was created inside a method only.

**Comment by prilaga** [comment]
@SwagatoMondal Thanks for the reply.
I do not use local variables for ads objects.
I did not change the code, but after several hours of debugging, I began to receive all callbacks. I played with "Test Mode Selective" in the account dashboard.
Do you guys have a big timeout for network connections? Perhaps this may cause the issue.
I will check callbacks in my other projects.

**Comment by sunilkuna5-inmobi** [comment]
@OlegTarashkevich  Thanks for the reply.

Closing the issue as the last follow-up is 2 years ago.
Please re-open the issue if the issue persists
