### ISSUE TITLE
how to use in react native

### ISSUE THREAD

**Issue by avinashclassy** [InMobi/sdk-sample-code-android#64]
Share example for integration of inmobi for react native

**Comment by RajSuvariya-InMobi** [comment]
@avinashclassy Currently we do no support integration with react native platform.

**Comment by avinashclassy** [comment]
Any other solution to use inmobi in react native

**Comment by RajSuvariya-InMobi** [comment]
As of today, we do not officially support any solution. However, we will consider this as a request and if we come up with the solution in the future then we will update this thread.

**Comment by avinashclassy** [comment]
@RajSuvariya-InMobi  thanks for the quick response.
