### ISSUE TITLE
The update of sdk version for banner ad sample seems to be missing.

### ISSUE THREAD

**Issue by KimReady** [InMobi/sdk-sample-code-android#70]
It's not a big issue, but I registered the issue to let you know that I'm missing it.

I think only the update of the sdk version on the banner ad sample is missing. Samples of different types of advertising seem to have been written in version 9.0.9 for banner ads alone, compared to those of version 9.1.0.

**Comment by rajsuvariya** [comment]
Hi, thank you for bringing this to our notice. We will fix it in the next PR.

**Comment by RajSuvariya-InMobi** [comment]
Closing this issue as it is fixed.
