### ISSUE TITLE
The test advertisement for banner is not rendered.

### ISSUE THREAD

**Issue by KimReady** [InMobi/sdk-sample-code-android#73]
Hi, I am inquiring because there is a problem while applying the ad for the InMobi banner on my app.
And I checked it on your sample app and it seems the same.

the problem is that Some of the `300 x 250` test ads are not rendered.
Looking at the adm, it is a banner advertisement including a video.

The problem is that normally `onAdLoadSucceeded()` is called, but the advertisement is not rendered.

Please check. I will cooperate if there is anything you need.

**Comment by RajSuvariya-InMobi** [comment]
Hi, thank you for reporting this issue. However, we would need more info on this to debug at our end.

1. Can you please confirm that this behavior is happening only if the video banner is in the adm and works fine for other non-video adm?
2. Can you please share the creative id of this adm? It will help us to find the creative id and do testing on our end. You can follow this guide for retrieving creative id https://support.inmobi.com/monetize/android-guidelines/android-testing-and-troubleshooting#page__retrieve-the-creativeid
3. Can you please share provide what kind of integration are you doing? Also, if it is not a direct integration with InMobi then please provide a primary mediation name as well.

**Comment by KimReady** [comment]
Thank you for your reply.

1. Yes. Among the ads in the same size(300x250), `.gif` ads work fine, but video banner ads don't work.
2. Sorry, I tried to check creative id, but it's hard to check because the video banner ad hasn't been loading. Have you taken any action?
3. I'm using the ads with InMobi directly.

In my opinion, this problem seems to be an issue that only occurs in test adm, and it is not a problem of sdk but of adm.

**Comment by RajSuvariya-InMobi** [comment]
@KimReady just to clarify further. You have mentioned that you are getting onAdLoadSucceeded(InMobiBanner banner, AdMetaInfo adInfo) callback then you can retrieve the creative id by querying adInfo.getCreativeID().

If you are not getting onAdLoadSucceeded callback then you can use onAdFetchSuccessful(InMobiBanner banner, AdMetaInfo adInfo) and retrieve the creative id by querying adInfo.getCreativeID().

Without creative id, we cannot debug further as on our end the test creatives are working fine. It may be a creative specific issue and we need a creative id to retrieve that creative.

**Comment by KimReady** [comment]
@RajSuvariya-InMobi 
OK. I got the creative id as you advised.

the creative id is `qml18N04HDetqvP3gyNXoR3ntAJUFMr5Bfn7oWhnthYyMU3MbJuKwA==`

It was obtained from the onAdLoadSucceeded() callback.
please check, thank you.

**Comment by RajSuvariya-InMobi** [comment]
Hi are you using the test mode for your placement id with which you are testing? 
if yes, then we are facing an issue with a particular video test creative for a 300 x 250 ad slot. Our team is working on fixing it. But the same issue won't happen in the production. If you are facing this issue on production / live placements then please revert back.

**Comment by KimReady** [comment]
Yes. I'm using the placement id just for test.
There has never been a problem in production yet.

I recently found a problem by raising the version of the InMobi SDK, and I just wanted to check whether it is a problem with adm or a problem with the latest SDK. I'm glad there won't be a problem in production.

Thank you for responding. You can close this issue.

**Comment by RajSuvariya-InMobi** [comment]
It's not an issue with the latest SDK, it is just that the test creative is not compatible with the latest SDK version and our team is working on that to update it. On production, you will get only compatible responses. 

Closing this issue as of now. Feel free to reopen if you face such issues on production.
