### ISSUE TITLE
It is not clear how to reload next rewarded ad after current ad closed or dismissed

### ISSUE THREAD

**Issue by nithinkolekar** [InMobi/sdk-sample-code-android#80]
In documentation at https://support.inmobi.com/monetize/android-guidelines/rewarded-video-ads-for-android it is mentioned

> Note
>
> Calling load() on the same interstitial ad after the onAdLoadSucceeded event is generated by the SDK is not guaranteed to request a fresh ad from the network. A fresh ad will only be fetched if either the previous ad was discarded by the SDK, or if the ad expired or the user cleared application data and caches.

In this repository also there is no code about reloading next rewarded ad after closing current ad.

**Comment by RajSuvariya-InMobi** [comment]
Hi @nithinkolekar 

You have to request the next ad same as you are requesting a fresh ad by calling load() method. You can use onAdDismissed() callback to listen to ad close the event. 

The note mentioned on the document dictates that if there is already an ad present locally with SDK which is not shown yet or not expired then SDK will not fetch a new ad from the server. But if you are loading the next ad only after the first ad is closed then it doesn't apply in your case.

Hope this clears your doubts. Please revert back in case of further doubts.

**Comment by sunilkuna5-inmobi** [comment]
Closing the issue as there is no follow up on the query @nithinkolekar
