### ISSUE TITLE
I have packaged the advertising SDK before, now I want to know how to package InMobi

### ISSUE THREAD

**Issue by hinthu29** [InMobi/sdk-sample-code-android#81]
I have packaged the advertising SDK before, now I want to know how to package InMobi.

This is the package code of mopub, I looked at Inmobi's Sample. It feels a bit like.

public class MopubNativeAdapter extends AdAdapter {
    private String adUnit;
    private RequestParameters parameters;
    private MoPubNative moPubNative;
    private NativeAd rawAd;
    private MoPubAdRendererProxy rendererProxy;
    private final static String TAG = "MopubNativeAdapter";

    public MopubNativeAdapter(Context context, String adUnit, String slot) {
        super(context, adUnit, slot);
        this.adUnit = adUnit;

        final EnumSet<RequestParameters.NativeAdAsset> desiredAssets = EnumSet.of(
                RequestParameters.NativeAdAsset.TITLE,
                RequestParameters.NativeAdAsset.TEXT,
                RequestParameters.NativeAdAsset.ICON_IMAGE,
                RequestParameters.NativeAdAsset.MAIN_IMAGE,
                RequestParameters.NativeAdAsset.CALL_TO_ACTION_TEXT);

        parameters = new RequestParameters.Builder()
                .desiredAssets(desiredAssets)
                .build();
    }

    @Override
    public void registerPrivacyIconView(View view) {

    }

    @Override
    public void loadAd(Context context, int num, IAdLoadListener listener) {
        mStartLoadedTime = System.currentTimeMillis();
        adListener = listener;
        moPubNative = new MoPubNative(context, this.adUnit, new MoPubNative.MoPubNativeNetworkListener() {
            @Override
            public void onNativeLoad(NativeAd nativeAd) {
                rawAd = nativeAd;
                mLoadedTime = System.currentTimeMillis();
                if (adListener != null) {
                    adListener.onAdLoaded(MopubNativeAdapter.this);
                }
                stopMonitor();
                if (mStartLoadedTime != 0) {
                }
                mStartLoadedTime = 0;
                MopubNativeAdapter.this.onAdLoaded();
            }

            @Override
            public void onNativeFail(NativeErrorCode errorCode) {
                if (adListener != null) {
                    adListener.onError(errorCode.toString());
                }
                stopMonitor();
                mStartLoadedTime = 0;
                MopubNativeAdapter.this.onError(String.valueOf(errorCode));
            }
        });
        rendererProxy = new MoPubAdRendererProxy();
        moPubNative.registerAdRenderer(rendererProxy);
        moPubNative.makeRequest(parameters);
        startMonitor();
    }

    @Override
    public String getAdType() {
        return AdType.AD_SOURCE_MOPUB;
    }

    @Override
    public Object getAdObject() {
        return rawAd;
    }

    @Override
    public void destroy() {
        if (isShowed()) {
            if (moPubNative != null) {
                moPubNative.destroy();
            }
            if (rawAd != null) {
                rawAd.destroy();
            }
        }
    }

    @Override
    public View getAdView(Context context, AdViewBinder viewBinder) {
        final ViewBinder mpViewBinder = new ViewBinder.Builder(viewBinder.layoutId)
                .titleId(viewBinder.titleId)
                .textId(viewBinder.textId)
                .mainImageId(viewBinder.mainMediaId)
                .iconImageId(viewBinder.iconImageId)
                .callToActionId(viewBinder.callToActionId)
                .privacyInformationIconImageId(viewBinder.privacymopubInformationId)
                .addExtras(viewBinder.extras)
                .build();
        final MoPubStaticNativeAdRenderer staticAdRender = new MoPubStaticNativeAdRenderer(mpViewBinder);
        rendererProxy.setRenderImpl(staticAdRender);
        rawAd.setMoPubNativeEventListener(new NativeAd.MoPubNativeEventListener() {
            @Override
            public void onImpression(View view) {

            }

            @Override
            public void onClick(View view) {
                FuseAdLoader.reportAdClick(MopubNativeAdapter.this);
            }
        });
        AdapterHelper helper = new AdapterHelper(context, 0, 5);
        View adview = helper.getAdView(null, null, rawAd, mpViewBinder);
        ImageView iv = adview.findViewById(viewBinder.mainMediaId);
        if (iv != null) {
            iv.setVisibility(View.VISIBLE);
        }
        registerViewForInteraction(adview);
        MopubNativeAdapter.this.onAdShowed();
        return adview;
    }

    @Override
    protected void onTimeOut() {
        if (adListener != null) {
            adListener.onError("TIME_OUT");
        }
    }
}

**Comment by RajSuvariya-InMobi** [comment]
You can follow this step by step integration guide https://support.inmobi.com/monetize/android-guidelines/

**Comment by sunilkuna5-inmobi** [comment]
Closing the issue as there is no follow up on the query
